{
 "title": "Real-Time Customer Behavior",
 "tags": [
  "real-time",
  "transactions"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "query": "SHOW TAG VALUES FROM \"raw_transactions\" WITH KEY = \"client_id\""
   }
  ]
 },
 "panels": [
  { "title": "Observations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Transaction Amount by Category",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "SELECT mean(\"avg_amount\") FROM \"avg_amount_by_category\" WHERE $timeFilter GROUP BY time(1m), \"merchant_category\" fill(null)"
    }
   ]
  },
  {
   "title": "Transaction Count by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "SELECT sum(\"txn_count\") FROM \"txn_count_by_region\" WHERE $timeFilter GROUP BY time(1m), \"region\" fill(null)"
    }
   ]
  },
  {
   "title": "Latest Transactions Sample",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "SELECT \"transaction_id\", \"client_id\", \"amount\", \"location\", \"region\", \"merchant_category\", \"device\"\nFROM \"raw_transactions\"\nWHERE $timeFilter\nORDER BY time DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Impossible Travel Fraud",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "SELECT \"client_id\", \"region_count\", \"regions_seen_str\"\nFROM \"impossible_travel_alerts\"\nWHERE $timeFilter  "
    }
   ]
  },
  {
   "title": "Suspicious Spending Spree Fraud",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "SELECT \"client_id\", \"categories_seen_str\", \"category_count\"\nFROM \"spending_spree_alerts\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "High velocity Fraud",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "SELECT \"client_id\", \"min_amount\", \"max_amount\"\nFROM \"low_high_velocity_alerts\"\nWHERE $timeFilter"
    }
   ]
  },
  { "title": "Client observations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Sum of the amounts per client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "SELECT CUMULATIVE_SUM(sum(\"amount\"))\nFROM \"raw_transactions\"\nWHERE \"client_id\" =~ /$client_id$/ AND $timeFilter\nGROUP BY time($__interval), \"client_id\""
    }
   ]
  }
 ]
}